title: HyPySpectral Documentation
description: Documentation for the HyPsySpectral Python package for Hyperspectral Image Analysis.
remote_theme: carlosperate/jekyll-theme-rtd

# Development server config, needed to load some of the content
webrick:
  headers:
    Access-Control-Allow-Origin: "*"

# Theme settings
site_author: Fraser Macfarlane
repo_url: 'https://github.com/HyPySpectral/hypyspectral.github.io'
edit_on_github: true
github_docs_folder: false
sticky_navigation: true
prev_next_buttons_location: both
search_enabled: true
hljs_style: github-gist
